bug: reproducible test-db-race
* The first test thread that acquires the DO_CLEANUP permit can still
  run after a second test thread has already created their ephemeral
  test db. This will accidentally "cleanup" the currently in-use test
  db.

Reproduce
=========

Run the database containers:

```bash
$ cd tests/
$ docker-compose up
```

Run the `test-db-race` tests. One test should fail.

```bash
$ cd tests/

$ ./x.py -e mysql_8_tokio --test mysql-test-db-race

test test_2 ... FAILED
test test_1 ... ok

failures:

---- test_2 stdout ----
created database _sqlx_test_database_5
thread 'test_2' panicked at 'failed to connect to test database: Database(MySqlDatabaseError { code: Some("42000"), number: 1049, message: "Unknown database '_sqlx_test_database_5'" })', /home/phlip9/dev/sqlx/sqlx-core/src/testing/mod.rs:245:10

$ ./x.py -e postgres_15_tokio --test postgres-test-db-race

test test_1 ... FAILED
test test_2 ... ok

failures:

thread 'test_1' panicked at 'failed to connect to test database: Database(PgDatabaseError { severity: Fatal, code: "3D000", message: "database \"_sqlx_test_69\" does not exist", detail: None, hint: None, position: None, where: None, schema: None, table: None, column: None, data_type: None, constraint: None, file: Some("postinit.c"), line: Some(941), routine: Some("InitPostgres") })', /home/phlip9/dev/sqlx/sqlx-core/src/testing/mod.rs:245:10
```